name: upload-cloud-storage Integration

on: [push]

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - id: upload
        name: upload folder
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: /home/runner/work/test-upload-gcs-action/test-upload-gcs-action/nested/in/here
          parent: false
          destination: ${{ secrets.UPLOAD_CLOUD_STORAGE_TEST_BUCKET }}
          credentials: ${{ secrets.UPLOAD_CLOUD_STORAGE_GCP_SA_KEY }}
      - name: get output
        run: echo '${{ steps.upload.outputs.uploaded }}'
